// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPNvfv8OickUsQuoDrg9-VXlis1RXxF7M',
    appId: '1:739059607767:web:a41aff34229fcc47736892',
    messagingSenderId: '739059607767',
    projectId: 'flutter-test-b9de4',
    authDomain: 'flutter-test-b9de4.firebaseapp.com',
    storageBucket: 'flutter-test-b9de4.firebasestorage.app',
    measurementId: 'G-9R2LZJ7XV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3PWt-qknAHSeRO7j2tNflnDfjgu-t9tM',
    appId: '1:739059607767:android:21edccc34bcb0c1f736892',
    messagingSenderId: '739059607767',
    projectId: 'flutter-test-b9de4',
    storageBucket: 'flutter-test-b9de4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC0ZB-MKzR2hEr8eXKgaM03XQIjQSV4y4',
    appId: '1:739059607767:ios:c0ffe926700e9b0a736892',
    messagingSenderId: '739059607767',
    projectId: 'flutter-test-b9de4',
    storageBucket: 'flutter-test-b9de4.firebasestorage.app',
    iosClientId: '739059607767-1vvrj68nag7dcfoetvs6urf2rtksn2kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC0ZB-MKzR2hEr8eXKgaM03XQIjQSV4y4',
    appId: '1:739059607767:ios:c0ffe926700e9b0a736892',
    messagingSenderId: '739059607767',
    projectId: 'flutter-test-b9de4',
    storageBucket: 'flutter-test-b9de4.firebasestorage.app',
    iosClientId: '739059607767-1vvrj68nag7dcfoetvs6urf2rtksn2kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPNvfv8OickUsQuoDrg9-VXlis1RXxF7M',
    appId: '1:739059607767:web:4cba15afe623b3bc736892',
    messagingSenderId: '739059607767',
    projectId: 'flutter-test-b9de4',
    authDomain: 'flutter-test-b9de4.firebaseapp.com',
    storageBucket: 'flutter-test-b9de4.firebasestorage.app',
    measurementId: 'G-CFP08YNES1',
  );

}