"""Refactor ORM for universal chats

Revision ID: 8cf35665c77b
Revises: ade0952749cc
Create Date: 2026-05-04 17:09:05.578416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf35665c77b'
down_revision = 'ade0952749cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_members',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='member', nullable=False),
    sa.Column('last_read_message_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.add_column('chats', sa.Column('type', sa.Enum('DIRECT', 'GROUP', name='chattype', native_enum=False), server_default='direct', nullable=False))
    op.add_column('chats', sa.Column('unique_tag', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'chats', ['unique_tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_column('chats', 'unique_tag')
    op.drop_column('chats', 'type')
    op.drop_table('chat_members')
    # ### end Alembic commands ###
